# Generated by Django 4.2.7 on 2024-02-18 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(max_length=255, verbose_name='Адрес получения заказа')),
                ('pickup_time', models.DateTimeField(verbose_name='Желательное время получения заказа')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Адрес доставки заказа')),
                ('delivery_time', models.DateTimeField(verbose_name='Желательное время доставки заказа')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Контактное лицо')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Контактный номер')),
                ('delivery_status', models.CharField(choices=[('В пути', 'В пути'), ('Доставлен', 'Доставлен'), ('Еще не забрали заказ', 'Еще не забрали заказ')], default='Еще не забрали заказ', max_length=20, verbose_name='Статус доставки')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Курьер')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
        ),
    ]
